# Generated by Django 4.1.5 on 2023-01-25 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('screens', models.IntegerField()),
                ('city', models.ManyToManyField(to='shows.city')),
            ],
        ),
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_no', models.IntegerField()),
                ('normal_seat_count', models.IntegerField()),
                ('executive_seat_count', models.IntegerField()),
                ('Theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('certification', models.CharField(choices=[('U', 'U'), ('UA', 'U/A'), ('A', 'A'), ('R', 'R')], max_length=3)),
                ('city', models.ManyToManyField(to='shows.city')),
            ],
        ),
    ]
