# Generated by Django 4.1.5 on 2023-01-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.ManyToManyField(to='shows.language'),
        ),
    ]
