# Generated by Django 4.1.5 on 2023-01-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_movies_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='city',
            field=models.ManyToManyField(related_name='mov_city', to='shows.city'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.ManyToManyField(related_name='mov_lang', to='shows.language'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='Theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_screen', to='shows.theatre'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='city',
            field=models.ManyToManyField(related_name='theatre_city', to='shows.city'),
        ),
    ]
