# Generated by Django 4.1.5 on 2023-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_seats_seat_type_delete_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='executive_seat_price',
            field=models.IntegerField(default=190),
        ),
        migrations.AddField(
            model_name='screen',
            name='normal_seat_price',
            field=models.IntegerField(default=190),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screen',
            name='executive_seat_count',
            field=models.IntegerField(default=120),
        ),
    ]
