# Generated by Django 4.1.5 on 2023-02-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_bookings_payment_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seats',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
